# default to true for all rules
default: true

# MD004/ul-style
MD004:
  # List style
  style: "sublist"

# MD033/no-inline-html
MD033:
  # Allowed elements
  allowed_elements: ["a", "div"]

# MD041/first-line-h1
MD041: false
