repos:
    - repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: "v0.13.0"
      hooks:
          - id: markdownlint-cli2

    - repo: https://github.com/abravalheri/validate-pyproject
      rev: "v0.19"
      hooks:
          - id: validate-pyproject

    - repo: https://github.com/PyCQA/docformatter
      rev: "v1.7.5"
      hooks:
          - id: docformatter
            additional_dependencies: [tomli]
            args: [-i, -e ./tests]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: "v0.6.3"
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
          - id: ruff-format

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.11.2"
      hooks:
          - id: mypy
            args: [--strict, --ignore-missing-imports]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "v4.6.0"
      hooks:
          - id: check-ast
          - id: check-builtin-literals
          - id: check-case-conflict
          - id: check-toml
          - id: check-yaml
          - id: detect-private-key
          - id: mixed-line-ending
          - id: requirements-txt-fixer
